import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../component/Banner'
import Card from '../component/Card'
import Image from 'next/image' 
import { fetchCoffeeData } from '../lib/coffe-data'

export async function getStaticProps() {
  
 const data = await fetchCoffeeData();

  return {
    props: {
       data,
    },
  }
}

export default function Home({ data }) {
  const handleOnClick = () => {
    console.log('click');
   }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
            <Banner button= "View shop nearby" handleOnClick={handleOnClick}/>
        <div className={styles.heroImage}>
            <Image src="/static/hero-image.png" width={700} height={400}/>
        </div>

        {data.length > 0 && (
        <>
       <h2 className={styles.heading2}>Palawan Coffee Shops</h2>
       <div className={styles.cardLayout}>
            {data.map(data => {
              return(<Card 
                  key={data.fsq_id}
                  card={data.name}
                  imgUrl={data.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                  href={`/store/${data.fsq_id}`}
                  className={styles.card}
                /> 
              )
            })}
        </div>
        </>
        )}
      </main>
    </div>
  )
}
